#!/bin/sh

set -e

cd "$(dirname "$0")/.."

ensure_exists() {
    if ! command -v "$1" >/dev/null 2>&1; then
        printf "Required command not available: %s\n" "$1"
        exit 1
    fi
}

ensure_exists "go"
ensure_exists "gofmt"
ensure_exists "git"

go mod download
